image: openjdk:11-stretch

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - java -version
  - command -v java
  - whereis java
  - which java

build:
  stage: build
  script: ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script: ./gradlew check
