image: ubuntu:bionic

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
  stage: build
  tags:
    - docker
  script:
    - java -version
    - command -v java
    - whereis java
    - which java
    - ./gradlew assemble

  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  tags:
    - docker
  script: ./gradlew check
