image: gradle:jdk8

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: /cache
  MAVEN_OPTS: "-Dmaven.repo.local=/.m2"

build:
  stage: build
  tags:
    - bioinfomethods
    - docker
    - mcri
  script:
    - ./gradlew clean build --build-cache --info
  artifacts:
    paths:
      - build/libs/*.jar
