image: gradle:jdk8

stages:
  - build

variables:
  GIT_STRATEGY: recursive
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  tags:
    - gradle:jdk8
    - docker
  script:
    - ./gradlew --build-cache -g /cache --info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradle
      - ui/node_modules
  artifacts:
    paths:
      - build/libs/*.jar
