image: gradle:jdk8

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_OPTS: '-Dorg.gradle.daemon=false'
  GRADLE_USER_HOME: /cache

build:
  stage: build
  tags:
    - gradle:jdk8
    - docker
  script:
    - ./gradlew clean --build-cache --info
  artifacts:
    paths:
      - build/libs/*.jar
