version: '3'

services:
    couchdb:
        image: couchdb:3.3
        environment:
            - COUCHDB_USER=${COUCHDB_USER:-admin}
            - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-admin_password}
        ports:
            - '5984:5984'
        volumes:
            - ./couchdb/data:/opt/couchdb/data
            - ./couchdb/local.ini:/opt/couchdb/etc/local.d/local.ini
