version: "3"

services:
  couchdb:
    image: apache/couchdb:3.2
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-couchdb}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-couchdb_password}
    ports:
      - "${COUCHDB_PORT:-5984}:5984"
    volumes:
      - ${COUCHDB_DATA_HOST_PATH:-./couchdb/data}:/opt/couchdb/data
      - ${COUCHDB_CONFIG_PATH:-./couchdb/local.d}:/opt/couchdb/etc/local.d
    healthcheck:
        test: [ "CMD-SHELL", "curl -L -s http://localhost:${COUCHDB_PORT:-5984}/_up | grep -q 'ok'" ]
