name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos recursively
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clear Gradle Cache
        if: ${{ github.event.inputs.clearCache == 'true' }}
        run: |
          rm -rf ~/.gradle/caches
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1.3.3
        with:
          gradle-version: 7.5.1
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: clean build installShadowDist --build-cache --info
